# Generated by Django 5.2.8 on 2025-11-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0004_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='ciudad_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='direccion_cliente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
