# Generated by Django 5.2.8 on 2025-11-20 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0005_compras_ciudad_cliente_compras_direccion_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estilista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.CharField(blank=True, help_text='Ej.: Corte, Color, Peinados', max_length=150, null=True)),
                ('experiencia_anos', models.PositiveIntegerField(default=0)),
                ('disponibilidad', models.CharField(blank=True, help_text='Horario o días disponibles', max_length=100, null=True)),
                ('certificado', models.BooleanField(default=False)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Estilistas',
            },
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='AppInventario.proveedores'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='estilista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios', to='AppInventario.estilista'),
        ),
    ]
