# Generated by Django 5.2.8 on 2025-11-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0007_rename_estilista_to_empleado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo o puesto del empleado', max_length=100, null=True),
        ),
    ]
