# Generated by Django 5.2.8 on 2025-11-21 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0012_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizado',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendados', to='AppInventario.servicio'),
        ),
    ]
