# Generated by Django 5.2.8 on 2025-11-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0013_serviciorealizado_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciorealizado',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
