# Generated by Django 5.2.8 on 2025-11-21 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0014_remove_serviciorealizado_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciorealizado',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='email_cliente',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='estilista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='AppInventario.empleado'),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='nombre_cliente',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='AppInventario.producto'),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='AppInventario.proveedores'),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendados', to='AppInventario.servicio'),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='telefono_cliente',
            field=models.CharField(default='', max_length=20),
        ),
    ]
