# Generated by Django 5.2.8 on 2025-11-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0017_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='11111111-1', max_length=12, unique=True, verbose_name='RUT'),
            preserve_default=False,
        ),
    ]
