# Generated by Django 5.2.8 on 2025-11-21 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0018_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciorealizado',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='AppInventario.producto'),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='AppInventario.proveedores'),
        ),
    ]
