# Generated by Django 5.2.8 on 2025-11-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0019_alter_serviciorealizado_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizado',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='fecha_servicio',
            field=models.DateField(),
        ),
    ]
