# Generated by Django 5.2.5 on 2025-11-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0020_serviciorealizado_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'ordering': ('nombre',),
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='empleados', to='AppInventario.especialidad', verbose_name='Especialidades'),
        ),
    ]
