# Generated by Django 5.2.5 on 2025-11-30 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0021_especialidad_alter_empleado_fecha_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='especialidades',
            field=models.ManyToManyField(blank=True, to='AppInventario.especialidad'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='AppInventario.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendas', to='AppInventario.empleado')),
                ('servicio_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='AppInventario.serviciorealizado')),
            ],
            options={
                'verbose_name_plural': 'Agendas',
                'ordering': ('fecha', 'hora_inicio'),
            },
        ),
    ]
