# Generated by Django 5.2.5 on 2025-11-30 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0022_especialidad_activo_alter_empleado_especialidades_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puede_agendar', models.BooleanField(default=False, help_text='Puede crear/agendar citas')),
                ('aparece_como_especialista', models.BooleanField(default=False, help_text='Aparece en el selector de especialistas al agendar')),
                ('puede_gestionar_inventario', models.BooleanField(default=False, help_text='Acceso/gestión del inventario')),
                ('puede_ver_compras', models.BooleanField(default=False, help_text='Puede ver historial de compras')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ('nombre',),
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='AppInventario.cargo'),
        ),
    ]
