# Generated by Django 5.2.5 on 2025-11-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0023_cargo_alter_empleado_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='aparece_como_especialista',
        ),
        migrations.AddField(
            model_name='cargo',
            name='puede_gestionar_empleados_servicios_proveedores',
            field=models.BooleanField(default=False, help_text='Puede gestionar empleados, servicios, proveedores y especialidades'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='puede_ver_clientes',
            field=models.BooleanField(default=False, help_text='Puede ver y gestionar clientes'),
        ),
    ]
