# Generated by Django 5.2.8 on 2025-11-30 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0025_empleado_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='especialidades_requeridas',
            field=models.ManyToManyField(blank=True, help_text='Especialidades necesarias para realizar este servicio', related_name='servicios', to='AppInventario.especialidad'),
        ),
    ]
