# Generated by Django 5.2.8 on 2025-11-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0026_servicio_especialidades_requeridas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sueldo del empleado', max_digits=10, null=True, verbose_name='Sueldo'),
        ),
    ]
