# Generated by Django 5.2.8 on 2025-11-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0027_empleado_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Para aplicar descuento del 20% en cumpleaños', null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
