# Generated by Django 5.2.8 on 2025-11-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0028_cliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ultimo_mes_descuento_cumpleanos',
            field=models.CharField(blank=True, help_text='Último mes/año en que usó el descuento (formato: YYYY-MM)', max_length=7, null=True, verbose_name='Último mes de descuento'),
        ),
    ]
