# Generated by Django 5.2.8 on 2025-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0029_cliente_ultimo_mes_descuento_cumpleanos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/fotos/', verbose_name='Foto de Perfil'),
        ),
    ]
