# Generated by Django 5.2.8 on 2025-12-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0031_productocatalogo_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocatalogo',
            name='proveedor',
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario')),
                ('unidad_medida', models.CharField(blank=True, help_text='Ej: kg, unidades, cajas', max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('codigo_producto', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código del Producto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='AppInventario.proveedores', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Proveedor',
                'verbose_name_plural': 'Productos de Proveedores',
                'ordering': ['proveedor__nombre', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='ProductoCatalogo',
        ),
    ]
