# Generated by Django 5.2.8 on 2025-12-02 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0032_remove_productocatalogo_proveedor_productoproveedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Factura')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Entrada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='AppInventario.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='AppInventario.proveedores')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró')),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
