# Generated by Django 5.2.8 on 2025-12-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0033_entradainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_promedio_actual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo promedio de compra actual', max_digits=10, verbose_name='Costo Promedio Actual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_habitual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_habituales', to='AppInventario.proveedores', verbose_name='Proveedor Habitual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=10, help_text='Cantidad mínima antes de alertar', verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='precio_compra_actual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio actual que cobra este proveedor', max_digits=10, null=True, verbose_name='Precio de Compra Actual'),
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_disponibles', to='AppInventario.producto', verbose_name='Producto del Inventario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio de Venta'),
        ),
    ]
