# Generated by Django 5.2.5 on 2025-12-04 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0035_solicitudcompra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='producto_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='AppInventario.productoproveedor', verbose_name='Producto de Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Modificación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_inventario', to='AppInventario.productoproveedor', verbose_name='Producto de Proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('propio', 'Producto Propio'), ('proveedor', 'Producto de Proveedor')], default='propio', max_length=20, verbose_name='Tipo de Producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, help_text='Ej: kg, unidades, cajas', max_length=50, null=True, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_creacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó'),
        ),
        migrations.AddField(
            model_name='producto',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó'),
        ),
        migrations.AlterField(
            model_name='compras',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='AppInventario.producto'),
        ),
    ]
