# Generated by Django 5.2.5 on 2025-12-04 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0036_compras_producto_proveedor_producto_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Nombre del Item')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('max_stack_size', models.PositiveIntegerField(default=1, help_text='Cantidad máxima que se puede apilar', verbose_name='Tamaño Máximo de Pila')),
                ('item_type', models.CharField(choices=[('ARMA', 'Arma'), ('ARMADURA', 'Armadura'), ('CONSUMIBLE', 'Consumible'), ('MATERIAL', 'Material'), ('MISION', 'Misión'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Tipo de Item')),
                ('image_url', models.CharField(blank=True, help_text='Ruta del ícono/imagen en el frontend', max_length=255, null=True, verbose_name='URL de Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item Personal',
                'verbose_name_plural': 'Items Personales',
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='UserInventorySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('slot_index', models.IntegerField(help_text='Posición o índice de la ranura (0-19 para 20 slots)', verbose_name='Índice de Ranura')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='AppInventario.itempersonal', verbose_name='Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_slots', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ranura de Inventario Personal',
                'verbose_name_plural': 'Ranuras de Inventario Personal',
                'ordering': ['user', 'slot_index'],
                'unique_together': {('user', 'slot_index')},
            },
        ),
    ]
