# Generated by Django 5.2.5 on 2025-12-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0037_itempersonal_userinventoryslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='zona',
            field=models.CharField(blank=True, help_text='Zona o ubicación donde se almacena el producto', max_length=100, null=True, verbose_name='Zona'),
        ),
    ]
