# Generated by Django 5.2.5 on 2025-12-05 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0039_add_zona_model_and_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_auditoria', models.DateField(verbose_name='Fecha de Auditoría')),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('observaciones_generales', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realiza la auditoría')),
            ],
            options={
                'verbose_name': 'Auditoría de Inventario',
                'verbose_name_plural': 'Auditorías de Inventario',
                'ordering': ['-fecha_auditoria', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAuditoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_sistema', models.IntegerField(help_text='Cantidad registrada en el sistema', verbose_name='Cantidad en Sistema')),
                ('conteo_fisico', models.IntegerField(help_text='Cantidad encontrada físicamente', verbose_name='Conteo Físico')),
                ('diferencia', models.IntegerField(help_text='Diferencia entre sistema y físico (automático)', verbose_name='Diferencia')),
                ('tipo_discrepancia', models.CharField(blank=True, choices=[('desaparecido', 'Desaparecido'), ('merma', 'Merma/Deterioro'), ('sobrante', 'Sobrante'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Discrepancia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('revisado', models.BooleanField(default=False, help_text='Indica si el producto fue revisado en el conteo físico', verbose_name='Revisado')),
                ('fecha_revision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='AppInventario.auditoriainventario', verbose_name='Auditoría')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='AppInventario.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Auditoría',
                'verbose_name_plural': 'Detalles de Auditoría',
                'ordering': ['producto__nombre'],
                'unique_together': {('auditoria', 'producto')},
            },
        ),
    ]
