# Generated by Django 5.2.5 on 2025-12-05 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0040_auditoriainventario_detalleauditoria'),
    ]

    operations = [
    ]
