# Generated by Django 5.2.5 on 2025-12-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0041_fix_auditoria_usuario_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleauditoria',
            name='conteo_fisico',
            field=models.IntegerField(default=0, help_text='Cantidad encontrada físicamente', verbose_name='Conteo Físico'),
        ),
        migrations.AlterField(
            model_name='detalleauditoria',
            name='diferencia',
            field=models.IntegerField(default=0, help_text='Diferencia entre sistema y físico (automático)', verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='detalleauditoria',
            name='tipo_discrepancia',
            field=models.CharField(blank=True, choices=[('desaparecido', 'Desaparecido'), ('vencido', 'Vencido'), ('merma', 'Merma/Deterioro'), ('sobrante', 'Sobrante'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Discrepancia'),
        ),
    ]
