# Generated by Django 5.2.5 on 2025-12-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0042_add_usuario_to_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleauditoria',
            name='tipo_discrepancia',
            field=models.CharField(blank=True, choices=[('sin_cambios', 'Sin Cambios'), ('desaparecido', 'Desaparecido'), ('vencido', 'Vencido'), ('merma', 'Merma/Deterioro'), ('sobrante', 'Sobrante'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de Discrepancia'),
        ),
    ]
