# Generated by Django 5.2.5 on 2025-12-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0043_alter_detalleauditoria_tipo_discrepancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('frutas', 'Frutas'), ('verduras', 'Verduras'), ('frutos_secos', 'Frutos Secos'), ('preelaborados', 'Preelaborados')], help_text='Categoría del producto', max_length=20, null=True, verbose_name='Categoría'),
        ),
    ]
