# Generated by Django 5.2.5 on 2025-12-06 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppInventario', '0045_empleadohistorial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creado', 'Creado'), ('editado', 'Editado'), ('eliminado', 'Eliminado')], max_length=20, verbose_name='Acción')),
                ('tipo_modelo', models.CharField(choices=[('producto', 'Producto'), ('proveedor', 'Proveedor'), ('cliente', 'Cliente'), ('empleado', 'Empleado'), ('servicio', 'Servicio'), ('cargo', 'Cargo'), ('especialidad', 'Especialidad'), ('entrada_inventario', 'Entrada de Inventario'), ('solicitud_compra', 'Solicitud de Compra'), ('producto_proveedor', 'Producto de Proveedor'), ('zona', 'Zona'), ('auditoria', 'Auditoría')], max_length=30, verbose_name='Tipo de Modelo')),
                ('nombre_objeto', models.CharField(max_length=200, verbose_name='Nombre del Objeto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('objeto_id', models.IntegerField(blank=True, help_text='ID del objeto afectado para referencia', null=True, verbose_name='ID del Objeto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ('-fecha',),
                'indexes': [models.Index(fields=['-fecha'], name='AppInventar_fecha_a3595d_idx'), models.Index(fields=['tipo_modelo', 'accion'], name='AppInventar_tipo_mo_07853c_idx')],
            },
        ),
    ]
